#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"


if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/DomePlugIns/"

cp "/tmp/NexDomeV3_X2/domelist NexDomeV3.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/NexDomeV3_X2/NexDomeV3.ui" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/NexDomeV3_X2/NexDome.png" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/NexDomeV3_X2/libNexDomeV3.dylib" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist NexDomeV3.txt"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/NexDomeV3.ui"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/NexDome.png"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/libNexDomeV3.dylib"
fi

rm -rf /tmp/NexDomeV3_X2
